added hw15_13.02.17
introkun/ITstep_B11016 pull request #5
Opened 2017-02-21 13:02 UTC by ArBond

2017-02-27 20:17 UTC, introkun requested changes

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +	int forExit = 1;
Можно было использовать bool вместо int

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +void sortByNumbers(int icqArray[], int phoneNubmersArray[], int firstFreeCellForRecording);
Можно завести 1 функицю сортировки и передать в нее критерий сортировки (enum SortBy {Icq, Phone})

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw15_13.02.17/№2/main2.c
> +		arr[indexOfLowElementForCoup] = buffer;
Заведите функцию swap()

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +void clearChar(char toContinue)
Не нужный аргумент функции toContinue

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +		printf("Slishkom bol'shoe chislo\n");
Число может быть и слишком маленьким, а ошибка будет про большое

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +void fillMatrix(int matrix[][COLUMN], int string, int column, int buffer)
buffer не нужен в качестве параметра функции

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +void fillMatrix(int matrix[][COLUMN], int string, int column, int buffer)
string -> row

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +int printfMenuAndChooseCourseOfMoving();
Почему возвращаемый тип не enum?

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +	int toContinue = 1;
bool

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +		}
Бесполезный switch. Игнорируется результат selection и вызывается ф-ция с теми же аргументами

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +		while (toContinue > 1 || toContinue < 0)
toContinue != 0 было бы проще

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw18_22.02.17/№1/main1.c
> +	fillArray(&startArray, &arraySize);
& не нужен для имен массивов

2017-02-27 20:17 UTC, introkun commented on Bondarenko/hw18_22.02.17/№2/main2.c
> +		int buffer = *(array + i);
Пишите функцию swap

2017-03-01 12:32 UTC, ArBond commented on Bondarenko/hw15_13.02.17/№2/main2.c
> +		arr[indexOfLowElementForCoup] = buffer;
просто переименовать turnOverElements() -> swap()?

2017-03-01 13:52 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +void fillMatrix(int matrix[][COLUMN], int string, int column, int buffer)
А как тогда передать число пользователя в функцию?
Думаю вы не так поняли т к название неудачное

2017-03-03 15:54 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +		while (toContinue > 1 || toContinue < 0)
тогда при при выборе пункта 1 будет выскакивать ошибка

2017-03-03 17:46 UTC, ArBond commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +void sortByNumbers(int icqArray[], int phoneNubmersArray[], int firstFreeCellForRecording);
+

2017-03-03 17:46 UTC, ArBond commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +	int forExit = 1;
+

2017-03-03 17:46 UTC, ArBond commented on Bondarenko/hw15_13.02.17/№1/main1.c
> +void clearChar(char toContinue)
+

2017-03-03 17:46 UTC, ArBond commented on Bondarenko/hw18_22.02.17/№2/main2.c
> +		int buffer = *(array + i);
+

2017-03-03 17:46 UTC, ArBond commented on Bondarenko/hw18_22.02.17/№1/main1.c
> +	fillArray(&startArray, &arraySize);
+

2017-03-03 17:54 UTC, ArBond commented on Bondarenko/hw15_13.02.17/№2/main2.c
> +		arr[indexOfLowElementForCoup] = buffer;
+

2017-03-03 17:57 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +		printf("Slishkom bol'shoe chislo\n");
+

2017-03-03 17:57 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +void fillMatrix(int matrix[][COLUMN], int string, int column, int buffer)
+

2017-03-03 18:01 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№1/main1.c
> +void fillMatrix(int matrix[][COLUMN], int string, int column, int buffer)
+

2017-03-03 18:15 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +	int toContinue = 1;
+

2017-03-03 18:24 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +int printfMenuAndChooseCourseOfMoving();
enum Сourse selection = printfMenuAndChooseCourseOfMoving(); я же в енам передаю число

2017-03-03 18:30 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +		}
+

2017-03-03 18:33 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +int printfMenuAndChooseCourseOfMoving();
если как-то лучше можно, то я не знаю как

2017-03-03 18:44 UTC, ArBond commented on Bondarenko/hw16_15.02.17/№2/main2.c
> +int printfMenuAndChooseCourseOfMoving();
+

2017-03-05 17:55 UTC, introkun approved these changes

2017-03-05 17:55 UTC, merged